services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      DEBUG: "False"
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
